export const khodamList = [
  "Si Raja Gombal",
  "Sang Penidur",
  "Si Penggoda Mie Instan",
  "Si Pencuri Gorengan",
  "Penguasa TikTok",
  "Si Penyedot Es Teh",
  "Penjaga Kasur",
  "Si Penakluk Lampu Merah",
  "Sang Pembisik Lelucon Garing",
  "Si Pemburu Diskon",
  "Penguasa Meme Lucu",
  "Si Penggemar Durian",
  "Sang Pembawa Payung",
  "Pengendali Remote TV",
  "Penjaga Cemilan Malam",
  "Sang Penimbun Stiker WhatsApp",
  "Penguasa Playlist Galau",
  "Si Tukang Ngaret",
  "Si Penggila Drama Korea",
  "Penyelamat Jajan Kantin",
  "Si Raja Gombal",
  "Sang Penidur",
  "Si Penggoda Mie Instan",
  "Si Pencuri Gorengan",
  "Penguasa TikTok",
  "Si Penyedot Es Teh",
  "Penjaga Kasur",
  "Si Penakluk Lampu Merah",
  "Pembisik Lelucon Garing",
  "Si Pemburu Diskon",
  "Penguasa Meme Lucu",
  "Si Penggemar Durian",
  "Sang Pembawa Payung",
  "Pengendali Remote TV",
  "Penjaga Cemilan Malam",
  "Sang Penimbun Stiker WhatsApp",
  "Penguasa Playlist Galau",
  "Si Tukang Ngaret",
  "Si Penggila Drama Korea",
  "Penyelamat Jajan Kantin",
  "Si Pemecah Daging Beku",
  "Si Penjaga Pintu",
  "Penguasa Chat Kosong",
  "Si Pemakan Bakso",
  "Sang Penghitung Bintang",
  "Penjaga Pintu Kulkas",
  "Si Penebar Kentut Bau",
  "Sang Pemanah Bantal",
  "Si Penjual Tawa",
  "Penjaga Wi-Fi Tetangga",
  "Si Pembaca Novel Misteri",
  "Sang Peminum Susu Coklat",
  "Si Pengorek Telinga",
  "Penjaga Kue Lebaran",
  "Si Pengejar Angin",
  "Penguasa Poci Teh",
  "Si Pembawa Sendok Ajaib",
  "Penjaga Lukisan Antik",
  "Si Pelompat Pagar",
  "Sang Pembaca Kartu Tarot",
  "Si Penjaga Obrolan",
  "Penguasa Komentar Receh",
  "Si Pengisi Air Galon",
  "Sang Pembisik Doa",
  "Penjaga Jembatan Cinta",
  "Si Penjelajah Mimpi",
  "Penguasa Es Krim",
  "Si Penata Rambut",
  "Penjaga Buku Diary",
  "Si Pembawa Pulpen Ajaib",
];
